// <auto-generated />
namespace DAOs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agregoanchodelavarilla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregoanchodelavarilla));
        
        string IMigrationMetadata.Id
        {
            get { return "201808012353314_Agrego ancho de la varilla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
