
SELECT * FROM dbo.Rod 

INSERT INTO dbo.Rod VALUES ('CHATA 2 KIRI', 2, 80, 1)
INSERT INTO dbo.Rod VALUES ('CHATA 3 KIRI', 3, 80, 1)
INSERT INTO dbo.Rod VALUES ('CHATA 3 BLANCO', 3, 80, 1)
INSERT INTO dbo.Rod VALUES ('CHATA 3 NEGRO', 3, 80, 1)
INSERT INTO dbo.Rod VALUES ('CHATA 4,5 KIRI', 4.5, 60, 1)
INSERT INTO dbo.Rod VALUES ('CHATA 6 KIRI', 6, 60, 1)

INSERT INTO dbo.Rod VALUES ('BOMBE 1,5 NEGRO BRILLOSO', 1.5, 60, 1)
INSERT INTO dbo.Rod VALUES ('BOMBE 2 NEGRO BRILLOSO', 2, 60, 1)

INSERT INTO dbo.Rod VALUES ('ITALIANA 2 ROBLE CLARO', 2, 60, 1)